routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function(){
    return redirect('admin/login');
});
Route::namespace('CRM')->prefix('admin')->group(function(){
    Route::get('/', function(){
        return redirect('admin/login');
    });

    Route::get('images/{image}', 'ImageController@see')->name('images.see');

    Auth::routes();

    Route::group(['middleware' => 'auth'], function(){
        Route::get('players', 'PlayerController@index')->name('players.index');

        Route::namespace('Accounts')->group(function(){
            Route::resource('accounts.billing_addresses', 'BillingAddressController', ['only' => [
                'index', 'store', 'update'
            ]]);

            Route::prefix('security_question')->group(function(){
                Route::get('/', 'SecurityQuestionController@index')->name('security_question.index');
                Route::get('list', 'SecurityQuestionController@fetchSecurityQuestionDatable')->name('security_question.dataTable');
                Route::post('create', 'SecurityQuestionController@create')->name('security_question.create');
                Route::post('delete/{id}', 'SecurityQuestionController@delete')->name('security_question.delete');
                Route::post('update/{id}', 'SecurityQuestionController@update')->name('security_question.update');
            });

            Route::prefix('accounts')->group(function(){
                Route::get('/', 'AccountsController@index')->name('accounts.index');
                Route::get('datatable', 'AccountsController@dataTable')->name('accounts.dataTable');
                Route::get('{account}', 'AccountsController@details')->name('accounts.details');
                Route::put('{account}', 'AccountsController@update')->name('accounts.update');
            });
        });

        Route::namespace('Application')->group(function(){
            Route::resource('applications', 'ApplicationController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);

            Route::get('applications/{dir}/{size}/{image}', 'ApplicationController@getImage')->name('applications.getImage');
        });

        Route::namespace('Charges')->prefix('charges')->group(function(){
            Route::get('regular', 'RegularChargesController@index')->name('regular.index');
            Route::post('regular/add', 'RegularChargesController@add')->name('regular.add');
            Route::put('regular/edit/{charge}', 'RegularChargesController@edit')->name('regular.edit');
            Route::get('membership', 'MembershipChargesController@index')->name('membership.index');
            Route::post('membership/add', 'MembershipChargesController@add')->name('membership.add');
            Route::put('membership/{membership}', 'MembershipChargesController@update')->name('membership.update');
            Route::get('promotion', 'PromotionChargesController@index')->name('promotion.index');

            Route::resource('membership.inclusions', 'MembershipInclusionsController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);

            Route::resource('membership.avatars', 'MembershipAvatarController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);
        });

        Route::namespace('Charts')->prefix('charts')->group(function(){
            Route::get('user_charge_range/{from}/{to}', 'UserChargeController@user_charge_range')->name('charts.user_charge_range');
            Route::get('sales_range/{from}/{to}', 'SalesController@sales_range')->name('charts.sales_range');
            Route::get('registered_users_range/{from}/{to}', 'RegisteredUsersController@registered_users_range')->name('charts.registered_users_range');
        });

        Route::namespace('CMS')->prefix('cms')->group(function(){
            Route::get('categories/json', 'CategoryController@json')->name('categories.json');
            Route::get('categories/parent/{parent}/positions', 'CategoryController@positions')->name('categories.positions');
            Route::get('categories/datatable', 'CategoryController@dataTable')->name('categories.dataTable');

            Route::resource('categories', 'CategoryController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);

            Route::post('contents/image/upload', 'ContentController@upload')->name('contents.upload');
            Route::get('contents/datatable', 'ContentController@dataTable')->name('contents.dataTable');
            Route::resource('contents', 'ContentController', ['except' => ['show']]);
        });

        Route::namespace('Customization')->prefix('customization')->group(function(){
            Route::get('avatars/json', 'AvatarController@json')->name('customization.avatars.json');

            Route::resource('avatars', 'AvatarController', ['only' => [
                'index', 'store', 'update'
            ]]);
        });

        Route::namespace('Dashboard')->prefix('dashboard')->group(function(){
            Route::get('/', 'DashboardController@index')->name('crm.dashboard.index');
            Route::get('/deposit_tickets', 'DepositTicketsController@tickets')->name('crm.dashboard.deposit.tickets');
            Route::get('/withdrawal_tickets', 'WithdrawalTicketsController@tickets')->name('crm.dashboard.withdrawal.tickets');
        });

        Route::namespace('Marketplace')->prefix('marketplace')->group(function(){
            Route::prefix('marketplace_currency')->group(function(){
                Route::get('/', 'MarketplaceCurrencyController@index')->name('marketplace_currency.index');
                Route::get('/datatable', 'MarketplaceCurrencyController@dataTable')->name('marketplace_currency.dataTable');
                Route::post('/save', 'MarketplaceCurrencyController@store')->name('marketplace_currency.store');
                Route::put('/update', 'MarketplaceCurrencyController@update')->name('marketplace_currency.update');
            });

            Route::get('/avatar/json', 'MarketplaceAvatarController@json')->name('marketplace_avatar.json');
            Route::get('/avatar/selectavatars', 'MarketplaceAvatarController@selectAvatars')->name('marketplace_avatar.selectavatars');
            Route::get('/avatar/', 'MarketplaceAvatarController@index')->name('marketplace_avatar.index');
            Route::get('/avatar/datatable', 'MarketplaceAvatarController@dataTable')->name('marketplace_avatar.datatable');
            Route::post('/avatar/save', 'MarketplaceAvatarController@store')->name('marketplace_avatar.store');
            Route::put('/avatar/update', 'MarketplaceAvatarController@update')->name('marketplace_avatar.update');
        });

        Route::namespace('Profile')->prefix('profile')->group(function(){
            Route::get('/{id}', 'ProfileController@index')->name('user.profile');
            Route::put('image/update/{id}', 'ProfileController@update')->name('user.profile.image');
        });

        Route::namespace('Security')->prefix('security')->group(function(){
            Route::get('permissions', 'PermissionController@index')->name('permissions.index');
            Route::post('permissions/add', 'PermissionController@add')->name('permissions.add');
            Route::put('permissions/edit', 'PermissionController@edit')->name('permissions.edit');
            Route::delete('roles/delete/{module}', 'RoleController@delete')->name('roles.delete');
            Route::get('roles/{role}/json', 'RoleController@json')->name('roles.json');
            Route::get('roles', 'RoleController@index')->name('roles.index');
            Route::post('roles/add', 'RoleController@add')->name('roles.add');
            Route::put('roles/{module}', 'RoleController@edit')->name('roles.edit');
            Route::get('assignuser', 'AssignUserController@index')->name('assignuser.index');
            Route::post('assignuser/add', 'AssignUserController@add')->name('assignuser.add');
            Route::delete('assignuser/delete/{assignuser}', 'AssignUserController@delete')->name('assignuser.delete');
            Route::put('assignuser/{assignuser}', 'AssignUserController@update')->name('assignuser.update');
            Route::put('assignuser/{assignuser}/password/reset', 'AssignUserController@passwordReset')->name('assignuser.passwordReset');
            Route::get('userimg/{dir}/{image}', 'AssignUserController@getImage')->name('assignuser.getImage');
        });

        Route::namespace('Status')->group(function(){
            Route::get('status/', 'StatusController@index')->name('status.index');
            Route::post('status/save', 'StatusController@store')->name('status.store');
            Route::get('status/edit/{id}', 'StatusController@edit')->name('status.edit');
            Route::put('status/update', 'StatusController@update')->name('status.update');
        });

        Route::namespace('Ticketing')->prefix('ticketing')->group(function(){
            Route::get('/', 'TicketingController@index')->name('ticketing.index');
            Route::get('/datatable', 'TicketingController@datatable')->name('ticketing.datatable');
            Route::get('/details/{id}', 'TicketingController@ticketDetails')->name('ticketing.details');
            Route::post('/track', 'TicketingController@trackTicket')->name('ticketing.track');
            Route::post('/reward', 'TicketingController@crmTicketAction')->name('ticketing.action');
        });

        Route::namespace('Inquiry')->prefix('inquiry')->group(function(){
            Route::get('/', 'InquiryController@index')->name('inquiry.index');

app/Http/Controllers/CRM/Application/ApplicationController.php
<?php

namespace App\Http\Controllers\CRM\Application;

use App\CRM\baccarat\Applications;
use App\Http\Controllers\CRM\NinePineController;
use App\Http\Requests\CRM\ApplicationRequest;
use App\CRM\NinepineModels\Status;
use Illuminate\Support\Facades\File;

class ApplicationController extends NinePineController
{
    public function index()
    {
        $data['page_title'] = 'Applications';
        $data['sub_title'] = '';
        $data['application_menu'] = true;

        $applications = Applications::join('Statuses', 'Applications.status_id', '=', 'Statuses.status_id')->get();
        $data['applications'] = $applications;

        $statuses = Status::where('status_type', 'Application')->get(['status_id', 'status_name'])->toArray();
        $data['statuses'] = $statuses;
        return view('CRM.application.application')->with($data);
    }

    public function store(ApplicationRequest $request)
    {
        $application = Applications::create([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'status_id' => $request->input('status_id')
        ]);

        if ($request->hasFile('image_landscape') && $request->hasFile('image_square')) {
            $application->app_image_470_260 = Applications::makeImage($request->file('image_landscape'), $application->application_id, Applications::$sizes['landscape']['width'], Applications::$sizes['landscape']['height']);
            $application->app_image_300_300 = Applications::makeImage($request->file('image_square'), $application->application_id, Applications::$sizes['square']['width'], Applications::$sizes['square']['height']);
        } else {
            $swal = trans('swal.application.create.image.error');

            return response()->json([
                config('response.status') => config('response.type.fail'),
                config('response.data') => compact('swal')
            ]);
        }
        $application->save();

        return response()->json([
            config('response.status') => config('response.type.success')
        ], 201);
    }

    public function update(ApplicationRequest $request, Applications $application)
    {
        $application->update([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'status_id' => $request->input('status_id')
        ]);

        if ($request->hasFile('image_landscape')) {
            $application->app_image_470_260 = Applications::makeImage($request->file('image_landscape'), $application->application_id, Applications::$sizes['landscape']['width'], Applications::$sizes['landscape']['height']);
        }

        if ($request->hasFile('image_square')) {
            $application->app_image_300_300 = Applications::makeImage($request->file('image_square'), $application->application_id, Applications::$sizes['square']['width'], Applications::$sizes['square']['height']);
        }
        $application->save();

        return response()->json([
            config('response.status') => config('response.type.success')
        ]);
    }

    public function destroy(Applications $application)
    {
        $affected = $application->getAffectedRelations();

        if (count($affected)) {
            return response()->json([
                config('response.status') => config('response.type.fail'),
                config('response.data') => compact('affected')
            ]);
        }
        $dir = storage_path("app/public/applications/$application->application_id");

        if (File::exists($dir)) {
            deleteDir($dir);
        }
        $application->delete();

        return response()->json([
            config('response.status') => config('response.type.success')
        ]);
    }

    public function getImage($dir, $size, $image)
    {
        $file = storage_path("app/public/applications/$dir/$size/$image");

        if (!File::exists($file)) {
            abort(404);
        }
        return response()->file($file);
    }
}

resources/views/CRM/application/forms/add.blade.php
<div class="modal fade" id="modal-add-app" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="form_app" id="form_app" action="{{ route('applications.store') }}"
                  enctype="multipart/form-data" method="post">
                {{ csrf_field() }}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Add Application</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name-input" class="control-label">Name</label>
                        <input type="text" class="form-control" id="name-input" name="name"
                               placeholder="Name">
                    </div>

                    <div class="form-group">
                        <label for="description-input-input" class="control-label">Description</label>
                        <input type="text" class="form-control" id="description-input"
                               name="description" placeholder="Description">
                    </div>

                    <div class="form-group">
                        <label for="image_landscape" class="control-label">Image <span class="text-muted">(Landscape: 470 x 260)</span></label>
                        <input type="file" class="form-control" id="image_landscape" name="image_landscape">
                    </div>

                    <div class="form-group">
                        <label for="image_square" class="control-label">Image <span class="text-muted">(Square: 300 x 300)</span></label>
                        <input type="file" id="image_square" class="form-control" name="image_square">
                    </div>
                    <div class="form-group">
                        <label for="status-input" class="control-label">Status</label>
                        <select id="status-input" class="form-control" name="status_id">
                            @foreach($statuses as $status)
                                <option value="{{ $status['status_id'] }}">{{ $status['status_name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    @usercan('add', 'applications.store')
                    <button type="submit" role="button" data-loading-text='{{ trans('loading.please_wait') }}'
                            class="btn btn-primary">Save
                    </button>
                    @endusercan
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/CRM/application/forms/edit.blade.php
<div class="modal fade" id="modal-edit-app" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="form_app_edit" id="form_app_edit" data-temp-action="/applications"
                  enctype="multipart/form-data" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Edit Application</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name-input" class="control-label">Name</label>
                        <input type="text" class="form-control" id="name-input" name="name"
                               placeholder="Name">
                    </div>

                    <div class="form-group">
                        <label for="description-input-input" class="control-label">Description</label>
                        <input type="text" class="form-control" id="description-input"
                               name="description" placeholder="Description">
                    </div>

                    <div class="form-group">
                        <label for="image_landscape" class="control-label">Image <span class="text-muted">(Landscape: 470 x 260)</span></label>
                        <input type="file" class="form-control" id="image_landscape" name="image_landscape">
                    </div>

                    <div class="form-group">
                        <label for="image_square" class="control-label">Image <span class="text-muted">(Square: 300 x 300)</span></label>
                        <input type="file" id="image_square" class="form-control" name="image_square">
                    </div>

                    <div class="form-group">
                        <label for="status-input" class="control-label">Status</label>
                        <select id="status-input" class="form-control" name="status_id">
                            @foreach($statuses as $status)
                                <option value="{{ $status['status_id'] }}">{{ $status['status_name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    @usercan('edit', 'applications.update')
                    <button type="submit" role="button" data-loading-text='{{ trans('loading.please_wait') }}'
                            class="btn btn-primary">Save changes
                    </button>
                    @endusercan
                </div>
            </form>
        </div>
    </div>
</div>