routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function(){
    return redirect('admin/login');
});
Route::namespace('CRM')->prefix('admin')->group(function(){
    Route::get('/', function(){
        return redirect('admin/login');
    });

    Route::get('images/{image}', 'ImageController@see')->name('images.see');

    Auth::routes();

    Route::group(['middleware' => 'auth'], function(){
        Route::get('players', 'PlayerController@index')->name('players.index');

        Route::namespace('Accounts')->group(function(){
            Route::resource('accounts.billing_addresses', 'BillingAddressController', ['only' => [
                'index', 'store', 'update'
            ]]);

            Route::prefix('security_question')->group(function(){
                Route::get('/', 'SecurityQuestionController@index')->name('security_question.index');
                Route::get('list', 'SecurityQuestionController@fetchSecurityQuestionDatable')->name('security_question.dataTable');
                Route::post('create', 'SecurityQuestionController@create')->name('security_question.create');
                Route::post('delete/{id}', 'SecurityQuestionController@delete')->name('security_question.delete');
                Route::post('update/{id}', 'SecurityQuestionController@update')->name('security_question.update');
            });

            Route::prefix('accounts')->group(function(){
                Route::get('/', 'AccountsController@index')->name('accounts.index');
                Route::get('datatable', 'AccountsController@dataTable')->name('accounts.dataTable');
                Route::get('{account}', 'AccountsController@details')->name('accounts.details');
                Route::put('{account}', 'AccountsController@update')->name('accounts.update');
            });
        });

        Route::namespace('Application')->group(function(){
            Route::resource('applications', 'ApplicationController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);

            Route::get('applications/{dir}/{size}/{image}', 'ApplicationController@getImage')->name('applications.getImage');
        });

        Route::namespace('Charges')->prefix('charges')->group(function(){
            Route::get('regular', 'RegularChargesController@index')->name('regular.index');
            Route::post('regular/add', 'RegularChargesController@add')->name('regular.add');
            Route::put('regular/edit/{charge}', 'RegularChargesController@edit')->name('regular.edit');
            Route::get('membership', 'MembershipChargesController@index')->name('membership.index');
            Route::post('membership/add', 'MembershipChargesController@add')->name('membership.add');
            Route::put('membership/{membership}', 'MembershipChargesController@update')->name('membership.update');
            Route::get('promotion', 'PromotionChargesController@index')->name('promotion.index');

            Route::resource('membership.inclusions', 'MembershipInclusionsController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);

            Route::resource('membership.avatars', 'MembershipAvatarController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);
        });

        Route::namespace('Charts')->prefix('charts')->group(function(){
            Route::get('user_charge_range/{from}/{to}', 'UserChargeController@user_charge_range')->name('charts.user_charge_range');
            Route::get('sales_range/{from}/{to}', 'SalesController@sales_range')->name('charts.sales_range');
            Route::get('registered_users_range/{from}/{to}', 'RegisteredUsersController@registered_users_range')->name('charts.registered_users_range');
        });

        Route::namespace('CMS')->prefix('cms')->group(function(){
            Route::get('categories/json', 'CategoryController@json')->name('categories.json');
            Route::get('categories/parent/{parent}/positions', 'CategoryController@positions')->name('categories.positions');
            Route::get('categories/datatable', 'CategoryController@dataTable')->name('categories.dataTable');

            Route::resource('categories', 'CategoryController', ['only' => [
                'index', 'store', 'update', 'destroy'
            ]]);

            Route::post('contents/image/upload', 'ContentController@upload')->name('contents.upload');
            Route::get('contents/datatable', 'ContentController@dataTable')->name('contents.dataTable');
            Route::resource('contents', 'ContentController', ['except' => ['show']]);
        });

        Route::namespace('Customization')->prefix('customization')->group(function(){
            Route::get('avatars/json', 'AvatarController@json')->name('customization.avatars.json');

            Route::resource('avatars', 'AvatarController', ['only' => [
                'index', 'store', 'update'
            ]]);
        });

        Route::namespace('Dashboard')->prefix('dashboard')->group(function(){
            Route::get('/', 'DashboardController@index')->name('crm.dashboard.index');
            Route::get('/deposit_tickets', 'DepositTicketsController@tickets')->name('crm.dashboard.deposit.tickets');
            Route::get('/withdrawal_tickets', 'WithdrawalTicketsController@tickets')->name('crm.dashboard.withdrawal.tickets');
        });

        Route::namespace('Marketplace')->prefix('marketplace')->group(function(){
            Route::prefix('marketplace_currency')->group(function(){
                Route::get('/', 'MarketplaceCurrencyController@index')->name('marketplace_currency.index');
                Route::get('/datatable', 'MarketplaceCurrencyController@dataTable')->name('marketplace_currency.dataTable');
                Route::post('/save', 'MarketplaceCurrencyController@store')->name('marketplace_currency.store');
                Route::put('/update', 'MarketplaceCurrencyController@update')->name('marketplace_currency.update');
            });

            Route::get('/avatar/json', 'MarketplaceAvatarController@json')->name('marketplace_avatar.json');
            Route::get('/avatar/selectavatars', 'MarketplaceAvatarController@selectAvatars')->name('marketplace_avatar.selectavatars');
            Route::get('/avatar/', 'MarketplaceAvatarController@index')->name('marketplace_avatar.index');
            Route::get('/avatar/datatable', 'MarketplaceAvatarController@dataTable')->name('marketplace_avatar.datatable');
            Route::post('/avatar/save', 'MarketplaceAvatarController@store')->name('marketplace_avatar.store');
            Route::put('/avatar/update', 'MarketplaceAvatarController@update')->name('marketplace_avatar.update');
        });

        Route::namespace('Profile')->prefix('profile')->group(function(){
            Route::get('/{id}', 'ProfileController@index')->name('user.profile');
            Route::put('image/update/{id}', 'ProfileController@update')->name('user.profile.image');
        });

        Route::namespace('Security')->prefix('security')->group(function(){
            Route::get('permissions', 'PermissionController@index')->name('permissions.index');
            Route::post('permissions/add', 'PermissionController@add')->name('permissions.add');
            Route::put('permissions/edit', 'PermissionController@edit')->name('permissions.edit');
            Route::delete('roles/delete/{module}', 'RoleController@delete')->name('roles.delete');
            Route::get('roles/{role}/json', 'RoleController@json')->name('roles.json');
            Route::get('roles', 'RoleController@index')->name('roles.index');
            Route::post('roles/add', 'RoleController@add')->name('roles.add');
            Route::put('roles/{module}', 'RoleController@edit')->name('roles.edit');
            Route::get('assignuser', 'AssignUserController@index')->name('assignuser.index');
            Route::post('assignuser/add', 'AssignUserController@add')->name('assignuser.add');
            Route::delete('assignuser/delete/{assignuser}', 'AssignUserController@delete')->name('assignuser.delete');
            Route::put('assignuser/{assignuser}', 'AssignUserController@update')->name('assignuser.update');
            Route::put('assignuser/{assignuser}/password/reset', 'AssignUserController@passwordReset')->name('assignuser.passwordReset');
            Route::get('userimg/{dir}/{image}', 'AssignUserController@getImage')->name('assignuser.getImage');
        });

        Route::namespace('Status')->group(function(){
            Route::get('status/', 'StatusController@index')->name('status.index');
            Route::post('status/save', 'StatusController@store')->name('status.store');
            Route::get('status/edit/{id}', 'StatusController@edit')->name('status.edit');
            Route::put('status/update', 'StatusController@update')->name('status.update');
        });

        Route::namespace('Ticketing')->prefix('ticketing')->group(function(){
            Route::get('/', 'TicketingController@index')->name('ticketing.index');
            Route::get('/datatable', 'TicketingController@datatable')->name('ticketing.datatable');
            Route::get('/details/{id}', 'TicketingController@ticketDetails')->name('ticketing.details');
            Route::post('/track', 'TicketingController@trackTicket')->name('ticketing.track');
            Route::post('/reward', 'TicketingController@crmTicketAction')->name('ticketing.action');
        });

        Route::namespace('Inquiry')->prefix('inquiry')->group(function(){
            Route::get('/', 'InquiryController@index')->name('inquiry.index');
            Route::get('/datatable', 'InquiryController@datatable')->name('inquiry.datatable');
            Route::post('/info', 'InquiryController@postInquiryInfo')->name('inquiry.info');

app/Http/Controllers/CRM/Customization/AvatarController.php
<?php

namespace App\Http\Controllers\CRM\Customization;

use App\CRM\baccarat\Applications;
use App\Http\Controllers\CRM\NinePineController;
use App\Http\Requests\CRM\AvatarRequest;
use App\CRM\NinepineModels\Avatar;
use App\CRM\NinepineModels\Status;
use Illuminate\Http\Request;

class AvatarController extends NinePineController
{
    public function json(Request $request)
    {
        $search = $request->query('search');
        $type = $request->query('type');
        $readonly = $request->query('readonly');
        $status_id = $request->query('status_id');
        $per_page = $request->query('per_page');
        $query = Avatar::latest('updated_at')->search($search);
        $except = json_decode($request->query('except'));

        if ($request->has('type')) {
            $query->where('type', $type);
        }

        if ($request->has('status_id')) {
            $query->where('status_id', $status_id);
        }

        if ($request->has('except')) {
            $query->whereNotIn('avatar_id', $except);
        }
        $avatars = $query->paginate($per_page)->appends([
            'search' => $search,
            'per_page' => $per_page,
            'readonly' => $readonly,
            'status_id' => $status_id,
            'type' => $type,
            'except' => $except,
        ]);
        $avatars = [
            'html' => (string)view('customization.avatar.avatars')->with([
                'avatars' => $avatars,
                'readonly' => $readonly == 'true' ? true : false
            ]),
            'links' => (string)$avatars->links()
        ];

        return response()->json([
            config('response.status') => config('response.type.success'),
            config('response.data') => compact('avatars'),
        ]);
    }

    public function index()
    {
        $data['customization_menu'] = true;
        $data['avatar_menu'] = true;
        $data['page_title'] = 'Avatars';
        $data['applications'] = Applications::all();
        $data['statuses'] = Status::where('status_type', 'Avatar')->get();
        $data['types'] = Avatar::$types;
        return view('CRM.customization.avatar.index')->with($data);
    }

    public function store(AvatarRequest $request)
    {
        $avatar = Avatar::create([
            'name' => $request->input('name'),
            'application_id' => $request->input('application_id'),
            'type' => $request->input('type'),
            'avatar' => Avatar::DEFAULT_AVATAR,
            'status_id' => $request->input('status_id')
        ]);

        if (!$request->hasFile('avatar') || !$avatar->makeAvatar($request->file('avatar'))) {
            $swal = trans('swal.avatar.create.image.error');

            return response()->json([
                config('response.status') => config('response.type.fail'),
                config('response.data') => compact('swal')
            ]);
        }
        return response()->json([
            config('response.status') => config('response.type.success')
        ], 201);
    }

    public function update(AvatarRequest $request, Avatar $avatar)
    {
        $avatar->update([
            'name' => $request->input('name'),
            'application_id' => $request->input('application_id'),
            'type' => $request->input('type'),
            'status_id' => $request->input('status_id')
        ]);

        if ($request->hasFile('avatar')) {
            if (!$avatar->makeAvatar($request->file('avatar'))) {
                $swal = trans('swal.avatar.update.image.error');

                return response()->json([
                    config('response.status') => config('response.type.fail'),
                    config('response.data') => compact('swal')
                ]);
            }
        }
        $avatar->save();

        return response()->json([
            config('response.status') => config('response.type.success')
        ]);
    }
}

resources/views/CRM/customization/avatar/forms/add.blade.php
<div class="modal fade" id="modal-add-avatar" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="form-add-avatar" id="form-add-avatar"
                  action="{{ route('avatars.store') }}"
                  enctype="multipart/form-data" method="post">
                {{ csrf_field() }}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Add Avatar</h4>
                </div>
                <div class="modal-body">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="add-name-input" class="control-label">Name</label>
                            <input type="text" class="form-control" id="add-name-input" name="name"
                                   placeholder="Name">
                        </div>

                        <div class="form-group">
                            <label for="add-avatar-input" class="control-label">Avatar <span class="text-muted">(1024 x 1024)</span></label>
                            <input type="file" class="form-control" id="add-avatar-input" name="avatar">
                        </div>

                        <div class="form-group">
                            <label for="add-application-select" class="control-label">Application</label>
                            <select id="add-application-select" class="form-control" name="application_id">
                                @foreach($applications as $application)
                                    <option value="{{ $application->application_id }}">{{ $application->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="add-type-select" class="control-label">Type</label>
                            <select id="add-type-select" class="form-control" name="type">
                                @foreach($types as $type)
                                    <option value="{{ $type }}">{{ $type }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="add-status-select" class="control-label">Status</label>
                            <select id="add-status-select" class="form-control" name="status_id">
                                @foreach($statuses as $status)
                                    <option value="{{ $status->status_id }}">{{ $status->status_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    @usercan('add', 'avatars.store')
                    <button type="submit" role="button" data-loading-text='{{ trans('loading.please_wait') }}'
                            class="btn btn-primary">Save
                    </button>
                    @endusercan
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/CRM/customization/avatar/forms/edit.blade.php
<div class="modal fade" id="modal-edit-avatar" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="form-edit-avatar" id="form-edit-avatar"
                  data-temp-action="/customization/avatars"
                  enctype="multipart/form-data" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Edit Avatar</h4>
                </div>
                <div class="modal-body">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="edit-name-input" class="control-label">Name</label>
                            <input type="text" class="form-control" id="edit-name-input" name="name"
                                   placeholder="Name">
                        </div>

                        <div class="form-group">
                            <label for="edit-avatar-input" class="control-label">Avatar <span class="text-muted">(1024 x 1024)</span></label>
                            <input type="file" class="form-control" id="edit-avatar-input" name="avatar">
                        </div>

                        <div class="form-group">
                            <label for="edit-application-select" class="control-label">Application</label>
                            <select id="edit-application-select" class="form-control" name="application_id">
                                @foreach($applications as $application)
                                    <option value="{{ $application->application_id }}">{{ $application->name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="edit-type-select" class="control-label">Type</label>
                            <select id="edit-type-select" class="form-control" name="type">
                                @foreach($types as $type)
                                    <option value="{{ $type }}">{{ $type }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="edit-status-select" class="control-label">Status</label>
                            <select id="edit-status-select" class="form-control" name="status_id">
                                @foreach($statuses as $status)
                                    <option value="{{ $status->status_id }}">{{ $status->status_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    @usercan('edit', 'avatars.update')
                    <button type="submit" role="button" data-loading-text='{{ trans('loading.please_wait') }}'
                            class="btn btn-primary">Save changes
                    </button>
                    @endusercan
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/CRM/customization/avatar/forms/select_avatar.blade.php
<div class="modal fade" id="modal-select-avatar" data-backdrop="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="row">
                    <div class="col-md-4 form-inline">
                        <span>Show</span>
                        <select name="per_page" id="avatars-per-page" class="form-control input-sm">
                            <option value="10">10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                        <span>entries</span>
                        <input type="hidden" id="current-url">
                    </div>
                    <div class="col-md-8 form-inline text-right">
                        <span>Search: </span>
                        <input type="text" name="search" id="avatars-search" class="form-control input-sm">
                    </div>
                    <input type="hidden" id="current-url">
                </div>
            </div>
            <div class="modal-body">
                <div class="row avatars"></div>
            </div>
            <div class="modal-footer">
                <div class="col-md-6 text-left">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
                <div class="col-md-6 text-right avatar-links"></div>
            </div>
        </div>
    </div>
</div>